import React, { useState } from 'react';
import { FileText, CheckCircle2, Circle, Download, Sparkles, Loader2, AlertCircle } from 'lucide-react';
import { openAIService } from '../../services/openaiService';

interface DocumentChecklistProps {
  renovationType: string;
  ownership: string;
  energyEfficiency: string;
  estimatedBudget: string;
}

interface ChecklistItem {
  text: string;
  checked: boolean;
}

const DocumentChecklist: React.FC<DocumentChecklistProps> = ({
  renovationType,
  ownership,
  energyEfficiency,
  estimatedBudget
}) => {
  const [checklist, setChecklist] = useState<ChecklistItem[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isGenerated, setIsGenerated] = useState(false);

  const handleGenerateChecklist = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const items = await openAIService.generateDocumentChecklist(
        renovationType,
        ownership,
        energyEfficiency
      );

      const checklistItems: ChecklistItem[] = items.map(text => ({
        text,
        checked: false
      }));

      setChecklist(checklistItems);
      setIsGenerated(true);
    } catch (err) {
      console.error('Error generating checklist:', err);
      setError(err instanceof Error ? err.message : 'Failed to generate checklist. Please try again.');

      // Fallback to static checklist if AI fails
      const fallbackChecklist = getFallbackChecklist();
      setChecklist(fallbackChecklist);
      setIsGenerated(true);
    } finally {
      setIsGenerating(false);
    }
  };

  const getFallbackChecklist = (): ChecklistItem[] => {
    const baseItems = [
      'Personal identification (Passport or Residence Permit)',
      'Proof of address (Meldebescheinigung)',
      'Last 3 salary slips or income proof',
      'Income tax statement (Einkommensteuerbescheid)',
      'Bank account statements (last 3 months)',
      'SCHUFA credit report',
      'Property ownership proof (Grundbuchauszug)',
      'Property valuation',
      'Contractor cost estimates (Kostenvoranschlag)',
      'Energy certificate (Energieausweis)'
    ];

    if (energyEfficiency === 'yes') {
      baseItems.push(
        'Energy consultant report (from Energieeffizienz-Experte)',
        'Individual renovation plan (iSFP)',
        'Energy efficiency calculations'
      );
    }

    return baseItems.map(text => ({ text, checked: false }));
  };

  const toggleChecklistItem = (index: number) => {
    setChecklist(prev =>
      prev.map((item, i) =>
        i === index ? { ...item, checked: !item.checked } : item
      )
    );
  };

  const handleDownloadChecklist = () => {
    const content = checklist
      .map((item, index) => `${index + 1}. ${item.checked ? '[✓]' : '[ ]'} ${item.text}`)
      .join('\n');

    const fullContent = `Document Checklist for Your Renovation Project
Generated: ${new Date().toLocaleDateString('de-DE')}

Renovation Type: ${renovationType}
Budget: ${estimatedBudget}
Energy Efficiency: ${energyEfficiency === 'yes' ? 'Yes' : 'No'}

${content}

---
Generated by RenovAlte Financing Assistant
`;

    const blob = new Blob([fullContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'renovation-document-checklist.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const completedCount = checklist.filter(item => item.checked).length;
  const totalCount = checklist.length;
  const progressPercentage = totalCount > 0 ? (completedCount / totalCount) * 100 : 0;

  if (!isGenerated) {
    return (
      <div className="bg-gradient-to-br from-emerald-50 to-blue-50 border border-emerald-200 rounded-lg p-6">
        <div className="flex items-start gap-4">
          <div className="bg-emerald-100 p-3 rounded-full">
            <Sparkles className="w-6 h-6 text-emerald-600" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">
              AI-Powered Document Checklist
            </h3>
            <p className="text-gray-700 mb-4">
              Get a personalized checklist of documents you'll need for your renovation financing application.
              Our AI will tailor the list based on your specific project requirements.
            </p>
            <button
              onClick={handleGenerateChecklist}
              disabled={isGenerating}
              className="bg-emerald-600 hover:bg-emerald-700 disabled:bg-gray-400 text-white font-semibold px-6 py-3 rounded-lg transition duration-200 flex items-center gap-2"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>Generating Your Checklist...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  <span>Generate My Document Checklist</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white border border-gray-200 rounded-lg shadow-sm">
      {/* Header */}
      <div className="bg-gradient-to-r from-emerald-600 to-emerald-700 p-6 rounded-t-lg">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-3">
            <FileText className="w-6 h-6 text-white" />
            <h3 className="text-xl font-bold text-white">Your Document Checklist</h3>
          </div>
          <button
            onClick={handleDownloadChecklist}
            className="bg-white/20 hover:bg-white/30 text-white px-4 py-2 rounded-lg transition flex items-center gap-2 text-sm"
          >
            <Download className="w-4 h-4" />
            Download
          </button>
        </div>

        {/* Progress Bar */}
        <div className="mt-4">
          <div className="flex items-center justify-between text-sm text-emerald-100 mb-2">
            <span>Progress</span>
            <span>{completedCount} of {totalCount} completed</span>
          </div>
          <div className="w-full bg-emerald-900/30 rounded-full h-2">
            <div
              className="bg-white h-2 rounded-full transition-all duration-300"
              style={{ width: `${progressPercentage}%` }}
            />
          </div>
        </div>
      </div>

      {/* Checklist Items */}
      <div className="p-6">
        {error && (
          <div className="mb-4 bg-amber-50 border border-amber-200 rounded-lg p-4 flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm text-amber-900 font-semibold">Note</p>
              <p className="text-sm text-amber-800">Showing standard checklist. {error}</p>
            </div>
          </div>
        )}

        <div className="space-y-3">
          {checklist.map((item, index) => (
            <div
              key={index}
              onClick={() => toggleChecklistItem(index)}
              className={`flex items-start gap-3 p-4 rounded-lg border-2 cursor-pointer transition-all ${
                item.checked
                  ? 'bg-emerald-50 border-emerald-300'
                  : 'bg-gray-50 border-gray-200 hover:border-emerald-200'
              }`}
            >
              <div className="flex-shrink-0 mt-0.5">
                {item.checked ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                ) : (
                  <Circle className="w-5 h-5 text-gray-400" />
                )}
              </div>
              <div className="flex-1">
                <p className={`text-sm ${item.checked ? 'text-gray-500 line-through' : 'text-gray-800 font-medium'}`}>
                  {item.text}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Completion Message */}
        {completedCount === totalCount && totalCount > 0 && (
          <div className="mt-6 bg-green-50 border border-green-200 rounded-lg p-4 flex items-start gap-3">
            <CheckCircle2 className="w-6 h-6 text-green-600 flex-shrink-0" />
            <div>
              <h4 className="font-semibold text-green-900 mb-1">All Set!</h4>
              <p className="text-sm text-green-800">
                You've checked off all documents. You're ready to apply for financing!
              </p>
            </div>
          </div>
        )}

        {/* Regenerate Button */}
        <div className="mt-6 pt-6 border-t border-gray-200">
          <button
            onClick={() => {
              setIsGenerated(false);
              setChecklist([]);
            }}
            className="text-emerald-600 hover:text-emerald-700 font-medium text-sm flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4" />
            Generate New Checklist
          </button>
        </div>
      </div>
    </div>
  );
};

export default DocumentChecklist;
