# Generated by Django 5.2.8 on 2026-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_contractor_caching_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="ai_description",
            field=models.CharField(
                blank=True,
                help_text="Short AI-generated description of contractor services",
                max_length=200,
                verbose_name="AI Description",
            ),
        ),
    ]
