# Generated by Django 5.2.9 on 2026-01-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contractor_ai_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovation_type', models.CharField(help_text='Type of renovation (bathroom, kitchen, etc.)', max_length=100)),
                ('property_location', models.CharField(blank=True, help_text='Property location', max_length=200, null=True)),
                ('form_data', models.JSONField(help_text='Complete form data submitted by user')),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, help_text='Total estimated cost in EUR', max_digits=12)),
                ('cost_breakdown', models.JSONField(help_text='Detailed cost breakdown')),
                ('cost_explanation', models.TextField(blank=True, help_text='AI explanation of costs', null=True)),
                ('financing_options', models.JSONField(blank=True, help_text='Recommended financing options', null=True)),
                ('financing_summary', models.TextField(blank=True, help_text='Summary of financing recommendations', null=True)),
                ('image_base64', models.TextField(blank=True, help_text='Base64 encoded generated image', null=True)),
                ('image_prompt', models.TextField(blank=True, help_text='Prompt used for image generation', null=True)),
                ('rag_enabled', models.BooleanField(default=False, help_text='Whether RAG was used for analysis')),
                ('rag_metadata', models.JSONField(blank=True, help_text='RAG analysis metadata', null=True)),
                ('user_identifier', models.CharField(blank=True, help_text='User identifier (email, session ID, etc.)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When result was saved')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When result was last updated')),
                ('result_name', models.CharField(blank=True, help_text='User-given name for this result', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this result', null=True)),
            ],
            options={
                'verbose_name': 'Financing Result',
                'verbose_name_plural': 'Financing Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_financ_created_b6d24f_idx'), models.Index(fields=['renovation_type'], name='core_financ_renovat_730df6_idx'), models.Index(fields=['user_identifier'], name='core_financ_user_id_c8fc9c_idx')],
            },
        ),
    ]
